global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'namespace']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'incident-responder'
  routes:
    - match:
        severity: critical
      receiver: 'incident-responder'
      continue: true
    - match:
        severity: warning
      receiver: 'incident-responder'

receivers:
  - name: 'incident-responder'
    webhook_configs:
      - url: 'http://incident-responder.monitoring.svc.cluster.local/webhook'
        send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'namespace']